name: Compiler

on:
  workflow_dispatch:

  # push:
    #branches: [ "master", "main", "*" ]
    # branches: [ "*" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependecies
        run: |
          sudo apt update
          # sudo apt dist-upgrade
          sed -i ':a;$!N;s/\n/ /;ta;' dependecies-install.list
          sudo apt-fast install -y $(cat dependecies-install.list)
          
      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
          
      - name: Update github
        run: |
          git config --local user.email "${{ secrets.USER }}@users.noreply.github.com"
          git config --local user.name "${{ secrets.USER }}"
          git add compilation/
          if [ -n "$(git commit -m "new version" | grep "nothing to commit")" ];then exit 0; fi
          git push

