name: Compiler

on:
  workflow_dispatch:

  # push:
    #branches: [ "master", "main", "*" ]
    # branches: [ "*" ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependecies
        run: |
          sudo apt update
          # sudo apt dist-upgrade
          sed -i ':a;$!N;s/\n/ /;ta;' dependecies-install.list
          sudo apt-fast install -y $(cat dependecies-install.list)
          
      # Tmate ##
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
          
      - name: Update github
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add compilation/
          if [ -n "$(git commit -m "new version" -a | grep "nothing to commit")" ];then exit 0; fi
          git push

      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}

